### PR TITLE
REST API for reset score functionality

### PR DESCRIPTION
**Pull request by Pichi00**
I added REST API for reset score functionality.

### CODE REVIEW

**Review by mvshao — APPROVED** [review]
It looks good enough for me! ✅

**Comment by VOID404** [comment]
Isn't `DELETE` a better choice for resetting score?
Definitely not `POST` - it's supposed to create a new resource
`PUT` maybe

**Comment by mvshao** [comment]
Some would say that extracting these from Server constructor
```
serv.router.HandleFunc("/", serv.TableMessagesHandler)
serv.router.HandleFunc("/reset", serv.ResetScoreHandler).Methods("POST")
```
into the function to initialize all endpoints is a better way, but your approach is also good.
```
func (s Server) EndpointInitialize(pass your router here) {
	router.HandleFunc(s.tableMessagesHandler, s.TableMessagesHandler).Methods("GET")
	router.HandleFunc(s.resetScoreHandler, s.ResetScoreHandler).Methods("GET")
}
```
In this way, you need to create all routers in main.go and delete it from the Server struct and also fill the struct with strings containing URLs to endpoints.

**Comment by Pichi00** [comment]
> Isn't `DELETE` a better choice for resetting score? Definitely not `POST` - it's supposed to create a new resource `PUT` maybe

In my opinion 'PUT' method will be the most appropriate in this case. 
However according to MDN documentation, 'POST' doesn't necessarily have to create new resource, but it can change state of existing one so we could also use it as well.   
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods

**Comment by VOID404** [comment]
> However according to MDN documentation, 'POST' doesn't necessarily have to create new resource, but it can change state of existing one so we could also use it as well

This documentation is talking about HTTP verbs. PR description is talking about REST API, so I'd expect it to match REST definitions, not just HTTP definitions

**Review by VOID404 — APPROVED** [review]

**Pull request merged**
